rabbitmq:
  port: 5672
  host: localhost
  username: guest
  password: guest
  listener:
    direct:
      default-requeue-rejected: true

spring:
  datasource:
    url: jdbc:h2:mem:payments_database;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update

jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    context-path: /payments
  port: 8082