server:
  servlet:
    context-path: /users
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:users_database;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
